export const SET_NAME = "SET_NAME";

export const USER_LOGIN = "USER_LOGIN";

export const COMPANY_DATA = "COMPANY_DATA";

export const ADD_RESPONSIBLE = "ADD_RESPONSIBLE";

export const REMOVE_RESPONSIBLE = "REMOVE_RESPONSIBLE";



export const CREATE_PLACE = "CREATE_PLACE"


export const LOGIN = "LOGIN"

export const LOGOUT = "LOGOUT"

export const TOKEN_EXPIRES_LOGOUT = "TOKEN_EXPIRES_LOGOUT"




// export const LOADING_TOGGLE_ACTION = "LOADING_TOGGLE_ACTION"
// export const LOGIN_CONFIRMED_ACTION = "LOGIN_CONFIRMED_ACTION"
// export const LOGIN_FAILED_ACTION = "LOGIN_FAILED_ACTION"
// export const LOGOUT_ACTION = "LOGOUT_ACTION"
// export const SIGNUP_CONFIRMED_ACTION = "SIGNUP_CONFIRMED_ACTION"
// export const SIGNUP_FAILED_ACTION = "SIGNUP_FAILED_ACTION"